<?php

namespace AppBundle\Repository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return array
     */
    public function findByCategorieId($id){
        $query =  $this->createQueryBuilder('film')
                       ->select('film')
                       ->where('film.categorie = :categorie')
                       ->orderBy('film.id')
                       ->setParameter('categorie', $id);
        return $query->getQuery()->getResult();
    }
}
